$notebook = @{
    cells = @(
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "# **1. Problem Statement**`n"
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "## 1.1 Business Context`n"
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "A sales forecast is a prediction of future sales revenue based on historical data, industry trends, and the status of the current sales pipeline. Businesses use the sales forecast to estimate weekly, monthly, quarterly, and annual sales totals. A company needs to make an accurate sales forecast as it adds value across an organization and helps the different verticals to chalk out their future course of action.`n",
                "`n",
                "Forecasting helps an organization plan its sales operations by region and provides valuable insights to the supply chain team regarding the procurement of goods and materials. An accurate sales forecast process has many benefits which include improved decision-making about the future and reduction of sales pipeline and forecast risks. Moreover, it helps to reduce the time spent in planning territory coverage and establish benchmarks that can be used to assess trends in the future."
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "## 1.2 Objective`n"
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "SuperKart is a retail chain operating supermarkets and food marts across various tier cities, offering a wide range of products. To optimize its inventory management and make informed decisions around regional sales strategies, SuperKart wants to accurately forecast the sales revenue of its outlets for the upcoming quarter.`n",
                "`n",
                "To operationalize these insights at scale, the company has partnered with a data science firm—not just to build a predictive model based on historical sales data, but to develop and deploy a robust forecasting solution that can be integrated into SuperKart’s decision-making systems and used across its network of stores."
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "## 1.3 Data Description`n"
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "The data contains the different attributes of the various products and stores. The detailed data dictionary is given below.`n",
                "`n",
                "- **Product_Id** - unique identifier of each product, each identifier having two letters at the beginning followed by a number.`n",
                "- **Product_Weight** - weight of each product`n",
                "- **Product_Sugar_Content** - sugar content of each product like low sugar, regular and no sugar`n",
                "- **Product_Allocated_Area** - ratio of the allocated display area of each product to the total display area of all the products in a store`n",
                "- **Product_Type** - broad category for each product`n",
                "- **Product_MRP** - maximum retail price of each product`n",
                "- **Store_Id** - unique identifier of each store`n",
                "- **Store_Establishment_Year** - year in which the store was established`n",
                "- **Store_Size** - size of the store depending on sq. feet like high, medium and low`n",
                "- **Store_Location_City_Type** - type of city in which the store is located like Tier 1, Tier 2 and Tier 3.`n",
                "- **Store_Type** - type of store depending on the products that are being sold there`n",
                "- **Product_Store_Sales_Total** - total revenue generated by the sale of that particular product in that particular store`n"
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "# **2. Installing and Importing the necessary libraries**`n"
            )
        },
        @{
            cell_type = "code"
            execution_count = $null
            metadata = @{}
            outputs = @()
            source = @(
                "!pip install pandas scikit-learn xgboost huggingface_hub joblib`n"
            )
        },
        @{
            cell_type = "code"
            execution_count = $null
            metadata = @{}
            outputs = @()
            source = @(
                "import os`n",
                "import pandas as pd`n",
                "from sklearn.model_selection import train_test_split`n",
                "from huggingface_hub import HfApi, login`n",
                "import joblib`n",
                "from sklearn.pipeline import Pipeline`n",
                "from sklearn.compose import ColumnTransformer`n",
                "from sklearn.preprocessing import StandardScaler, OneHotEncoder`n",
                "from xgboost import XGBRegressor`n",
                "from sklearn.metrics import mean_squared_error, r2_score`n"
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "# **3. Data Loading and Hugging Face Registration**`n"
            )
        },
        @{
            cell_type = "code"
            execution_count = $null
            metadata = @{}
            outputs = @()
            source = @(
                "# Authenticate with Hugging Face using the provided token`n",
                "print('Logging into Hugging Face...')`n",
                "import os`n",
                "token = os.getenv('HF_TOKEN')`n",
                "if token:`n",
                "    login(token)`n",
                "else:`n",
                "    from huggingface_hub import notebook_login`n",
                "    notebook_login()`n",
                "`n",
                "# Load the dataset directly from the local data folder`n",
                "print('Loading SuperKart dataset...')`n",
                "df = pd.read_csv('data/SuperKart.csv')`n",
                "display(df.head())`n",
                "print(f\"Shape of the dataset: {df.shape}\")`n",
                "df.info()`n"
            )
        },
        @{
            cell_type = "code"
            execution_count = $null
            metadata = @{}
            outputs = @()
            source = @(
                "# Register the initial dataset to the Hugging Face dataset space`n",
                "api = HfApi()`n",
                "print('Uploading raw data to Hugging Face Dataset Space...')`n",
                "api.upload_file(`n",
                "    path_or_fileobj='data/SuperKart.csv',`n",
                "    path_in_repo='data/SuperKart.csv',`n",
                "    repo_id='pvinayv/superkart-dataset',`n",
                "    repo_type='dataset'`n",
                ")`n",
                "print('Upload complete.')`n"
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "# **4. Data Preparation & Split Registration**`n"
            )
        },
        @{
            cell_type = "code"
            execution_count = $null
            metadata = @{}
            outputs = @()
            source = @(
                "# 1. Handle Missing Values`n",
                "df['Product_Weight'] = df['Product_Weight'].fillna(df['Product_Weight'].mean())`n",
                "df['Store_Size'] = df['Store_Size'].fillna('Medium')`n",
                "`n",
                "# 2. Standardize Categorical Variables`n",
                "df['Product_Sugar_Content'] = df['Product_Sugar_Content'].replace({'low fat': 'Low Fat', 'LF': 'Low Fat', 'reg': 'Regular'})`n",
                "`n",
                "# 3. Train-Test Split`n",
                "train, test = train_test_split(df, test_size=0.2, random_state=42)`n",
                "train.to_csv('data/train.csv', index=False)`n",
                "test.to_csv('data/test.csv', index=False)`n",
                "print(f'Train shape: {train.shape}, Test shape: {test.shape}')`n"
            )
        },
        @{
            cell_type = "code"
            execution_count = $null
            metadata = @{}
            outputs = @()
            source = @(
                "# Upload processed splits to Hugging Face Dataset space`n",
                "api.upload_file(path_or_fileobj='data/train.csv', path_in_repo='train.csv', repo_id='pvinayv/superkart-dataset', repo_type='dataset')`n",
                "api.upload_file(path_or_fileobj='data/test.csv', path_in_repo='test.csv', repo_id='pvinayv/superkart-dataset', repo_type='dataset')`n"
            )
        },
        @{
            cell_type = "markdown"
            metadata = @{}
            source = @(
                "# **5. Model Training and MLOps Deployment**`n"
            )
        },
        @{
            cell_type = "code"
            execution_count = $null
            metadata = @{}
            outputs = @()
            source = @(
                "# Separate features (X) and target variable (y)`n",
                "X_train = train.drop(columns=['Product_Store_Sales_Total', 'Product_Id', 'Store_Id'])`n",
                "y_train = train['Product_Store_Sales_Total']`n",
                "X_test = test.drop(columns=['Product_Store_Sales_Total', 'Product_Id', 'Store_Id'])`n",
                "y_test = test['Product_Store_Sales_Total']`n",
                "`n",
                "categorical_features = ['Product_Sugar_Content', 'Product_Type', 'Store_Size', 'Store_Location_City_Type', 'Store_Type']`n",
                "numeric_features = ['Product_Weight', 'Product_Allocated_Area', 'Product_MRP', 'Store_Establishment_Year']`n",
                "`n",
                "preprocessor = ColumnTransformer(`n",
                "    transformers=[`n",
                "        ('num', StandardScaler(), numeric_features),`n",
                "        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)`n",
                "    ])`n",
                "`n",
                "pipeline = Pipeline(steps=[`n",
                "    ('preprocessor', preprocessor),`n",
                "    ('model', XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42))`n",
                "])`n",
                "`n",
                "pipeline.fit(X_train, y_train)`n"
            )
        },
        @{
            cell_type = "code"
            execution_count = $null
            metadata = @{}
            outputs = @()
            source = @(
                "# Evaluate model performance`n",
                "y_pred = pipeline.predict(X_test)`n",
                "rmse = mean_squared_error(y_test, y_pred) ** 0.5`n",
                "r2 = r2_score(y_test, y_pred)`n",
                "print(f'RMSE: {rmse:.2f}')`n",
                "print(f'R2 Score: {r2:.4f}')`n"
            )
        },
        @{
            cell_type = "code"
            execution_count = $null
            metadata = @{}
            outputs = @()
            source = @(
                "# Serialize and Register the model`n",
                "joblib.dump(pipeline, 'xgboost_model.pkl')`n",
                "api.upload_file(`n",
                "    path_or_fileobj='xgboost_model.pkl',`n",
                "    path_in_repo='xgboost_model.pkl',`n",
                "    repo_id='pvinayv/superkart-model',`n",
                "    repo_type='model'`n",
                ")`n"
            )
        }
    )
    metadata = @{
        kernelspec = @{
            display_name = "Python 3"
            language = "python"
            name = "python3"
        }
        language_info = @{
            name = "python"
            version = "3.9.0"
        }
    }
    nbformat = 4
    nbformat_minor = 4
}
$notebook | ConvertTo-Json -Depth 10 | Out-File -Encoding utf8 "MLOps_Sales_Forecast.ipynb"
